spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.20.103:3306/rain?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: dms01
    password: Cse@dms01

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.rumofuture.nemo.model.domain
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.rumofuture.nemo.repository: debug
